# Generated by Django 2.0.4 on 2018-04-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20180426_0418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('following', 'follower')},
        ),
    ]
