# Generated by Django 2.0.4 on 2018-04-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_auto_20180426_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_messages', to='user_info.User'),
        ),
    ]
