# Generated by Django 2.0.4 on 2018-04-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_photos', to='user_info.User'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(upload_to='apps/user_info/templates/user_info/media'),
        ),
    ]
