# Generated by Django 2.0.4 on 2018-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_auto_20180427_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(upload_to='media/%Y/%m'),
        ),
    ]
